### ISSUE TITLE
How do I change the access token/api key?

### ISSUE THREAD

**Issue by wutmikee** [fraterblack/mailchimpv3-laravel#1]
For example, my application handles/manages user's accounts on their behalf. So each account request will have a different api key (i.e. access token) that will need to be used.

Or would I just run it like so?

```
$mailchimp = new Mailchimp($access_token);
$mailchimp->post(...
```

**Comment by fraterblack** [comment]
This package is a simple service provider to register a Mailchimp instance to be set up with the API-key.
Then, the IoC-container can be used to get a Mailchimp API instance ready for use.
I think that your application could use the [drewm/mailchimp-api](https://github.com/drewm/mailchimp-api) package directly without my package.

**Comment by wutmikee** [comment]
Right, makes sense. Thanks for your help!
